### ISSUE TITLE
Preview does not load correct data until Search is clicked

### ISSUE THREAD

**Issue by TheInvisibleMage** [SkinnyDevi/webui_tavernai_charas#6]
Description:
- When a character is selected and the Preview button is clicked from within the "Online Characters" tab, the UI correctly swaps to the "Card Previewer" tab. However, the data/image shown within that tab (apart from the Url) does not appear until "Search" is clicked within that tab.
- - If no other character was previously previewed in this session, all fields (except the selected character's Url) simply show "Error" until Search is clicked.
- - If a different character was previously loaded by clicking the search button, that previous character's data is shown instead.

Repro:
- Select a character card from the "Online Characters" tab, and click "Preview".

Acceptance Criteria:
- Expected: When clicking "Preview", the data/image of the character you wish to preview is loaded immediately into the "Card Previewer" tab.
- Actual: The data of the previously previewed character is seen until "Search" is clicked. If there was no previously previewed character, "Error" is shown instead.

Additional Context:

- Branch: Master
- Commit: 67b5f211fa1e3f9211b8e5c655c834bb68249313

**Comment by SkinnyDevi** [comment]
Hi there! Sorry for the very late response. 

I'm currently trying to reproduce the steps to recreate your issue to no avail.

If you could specify a situation where this could happen, as the situtations you mentioned weren't useful, it'd be much appreciated.

My results when reproducing your steps:
- Upon clicking Preview, tab swaps correctly and card information displays according, as well as correct card image.
- If trying to Preview another card while the Card Previewer tab has already a card, the card information is swapped correctly in the previewer.

It may seem like a dumb suggestion, but have you tried/have your text-generation-webui build to the latest update?
Hope that helps.

**Comment by SkinnyDevi** [comment]
I will now close this issue as it has been fixed/can't be reproduced in the latest version.

**Comment by TheInvisibleMage** [comment]
Apologies for the delay in my response.
I can confirm this issue is still present for me, but only rarely, when I access the UI via Firefox. Chrome does not show the issue. It seems mostly resolved.
Thank you for work on this!

**Comment by SkinnyDevi** [comment]
> Apologies for the delay in my response.
> 
> I can confirm this issue is still present for me, but only rarely, when I access the UI via Firefox. Chrome does not show the issue. It seems mostly resolved.
> 
> Thank you for work on this!

Okay, thank you for the feedback. If it happens again, please reopen the issue with the specific details. Thank you!
